### PR TITLE
StartPad with 0

### PR DESCRIPTION
**Pull request by Crow2525-pp**
Added '0' padding to 2, 3, and 4 digs ANZSIC and Num Col to Division Alpha to address issue 3 & 4.

### CODE REVIEW

**Comment by asiripanich** [comment]
Hi @Crow2525-pp, thank you for the PR. 

May I get your opinion on whether we should treat those number columns as numeric or character? The reason I'm asking is because all the values in those columns are numeric. Is it better to leave them as they are?

@williamlai2 would this PR affect your code? specifically https://github.com/runapp-aus/strayr?

**Comment by williamlai2** [comment]
Looking at https://github.com/runapp-aus/strayr/blob/master/data-raw/create_anzsic2006.R this change would break the code because `anzsic_class_code` and other bits rely on the `group_code` in the original file being a double that gets converted to an integer, whereas with the padded 0, they would be strings. This could all be fixed though.

@daviddiviny wrote the original code for this.

It is slightly related to issues in https://github.com/runapp-aus/strayr/issues/91 as well. A workaround could be having a different source for the ANZSIC codes too.

**Comment by daviddivinynous** [comment]
Yes, this is worth fixing I think.

**Comment by asiripanich** [comment]
Fixed in #7.

**Pull request closed without merging**
